spring.application.name=agritech-backend

spring.datasource.url=jdbc:mysql://agritech.mysql.database.azure.com:3306/agritechdb

spring.datasource.username=mysqladmin

spring.datasource.password=Nvssc007

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true